econml 0.15.0 ❄️
AnacondaRecipes/econml-feedstock pull request #2
Opened 2024-03-21 21:33 UTC by psteyer

econml 0.15.0 ❄️

**Destination channel:** Snowflake

### Links

- [4217](https://anaconda.atlassian.net/browse/PKG-4217) 
- [Upstream repository](https://github.com/py-why/EconML)
- [Upstream changelog/diff](https://github.com/py-why/EconML/compare/v0.13.1...v0.15.0)

### Explanation of changes:

-

2024-03-21 21:34 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_afaee3fcmb/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:58: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
- clone/recipe/meta.yaml:58: missing_dev_url: The recipe is missing a dev_url
- clone/recipe/meta.yaml:58: missing_documentation: The recipe is missing a doc_url or doc_source_url
- clone/recipe/meta.yaml:30: missing_wheel: For pypi packages, wheel should be present in the host section
- clone/recipe/meta.yaml:58: missing_license_family: The recipe is missing the `about/license_family` key.
===== Final Report: =====
5 Errors and 1 Warning were found

</details>

2024-03-22 16:48 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_07w05qfrwm/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:58: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:58: missing_documentation: The recipe is missing a doc_url or doc_source_url
- clone/recipe/meta.yaml:30: missing_wheel: For pypi packages, wheel should be present in the host section
- clone/recipe/meta.yaml:58: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
- clone/recipe/meta.yaml:58: missing_dev_url: The recipe is missing a dev_url
===== Final Report: =====
5 Errors and 1 Warning were found

</details>

2024-03-22 18:18 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_f96b9h9wc9/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:60: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:60: missing_documentation: The recipe is missing a doc_url or doc_source_url
- clone/recipe/meta.yaml:60: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
- clone/recipe/meta.yaml:30: missing_wheel: For pypi packages, wheel should be present in the host section
- clone/recipe/meta.yaml:60: missing_dev_url: The recipe is missing a dev_url
===== Final Report: =====
5 Errors and 1 Warning were found

</details>

2024-03-22 18:46 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_4bj2vrhxnf/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:59: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:30: missing_wheel: For pypi packages, wheel should be present in the host section
- clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
- clone/recipe/meta.yaml:59: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:59: missing_dev_url: The recipe is missing a dev_url
- clone/recipe/meta.yaml:59: missing_documentation: The recipe is missing a doc_url or doc_source_url
===== Final Report: =====
5 Errors and 1 Warning were found

</details>

2024-03-22 19:05 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_e2rk7xidbs/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:60: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:60: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
- clone/recipe/meta.yaml:60: missing_dev_url: The recipe is missing a dev_url
- clone/recipe/meta.yaml:60: missing_documentation: The recipe is missing a doc_url or doc_source_url
- clone/recipe/meta.yaml:30: missing_wheel: For pypi packages, wheel should be present in the host section
===== Final Report: =====
5 Errors and 1 Warning were found

</details>

2024-03-22 21:02 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_0bn3fek8l8/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:62: missing_description: The recipe is missing a description
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-25 22:49 UTC, danpetry approved these changes

2024-03-25 22:51 UTC, danpetry commented
Adding upstream tests would be nice if poss: https://github.com/py-why/EconML/tree/v0.15.0/econml/tests

2024-03-26 00:12 UTC, lorepirri approved these changes

2024-03-26 00:12 UTC, lorepirri commented on recipe/meta.yaml
>      - cython
what about
```
    "scipy",
    "cython<3" # Our native code has several incompatibilities with Cython 3
```
https://github.com/py-why/EconML/blob/479362aceb3205b6515adf5084f59a24ea79785d/pyproject.toml#L87-L88

2024-03-26 21:06 UTC, lorepirri commented
@boldorider4 I'll take on this one as well and add upstream tests

2024-03-26 21:06 UTC, lorepirri reviewed
adding upstream tests

2024-03-27 01:01 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_afwldjg8s2/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:27: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-27 13:09 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_b0ek3pnr3u/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:28: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-27 13:19 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_6b8u6sexuo/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:28: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-27 22:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_f8ur74m_o6/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:28: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-28 18:36 UTC, boldorider4 approved these changes

2024-03-28 23:31 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_2c6g6c1sxn/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:28: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:83: invalid_url: https://econml.azurewebsites.net/ : Not reachable: 403
===== Final Report: =====
1 Error and 1 Warning were found

</details>

2024-03-28 23:49 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_ac2b_2c07e/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:31: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-29 00:03 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_86v7qc8hf5/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-29 14:14 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +  skip: True  # [osx and 64]
```suggestion
  skip: True  # [osx]
```
It crashes (real hard kernel crash) our osx-arm64 machines.

2024-03-29 14:15 UTC, JeanChristopheMorinPerso requested changes

2024-03-29 14:15 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +  skip: True  # [osx and 64]
```suggestion
  skip: True  # [osx]
```
It crashes (real hard kernel crash) our osx-arm64 machines.

2024-04-02 10:33 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_99kldo0d5i/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-04 07:02 UTC, skupr-anaconda commented on recipe/meta.yaml
>    license: BSD-3-Clause
```suggestion
  license: MIT AND BSD-3-Clause
```
see https://github.com/py-why/EconML/blob/v0.15.0/LICENSE

2024-04-04 07:02 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  license_family: BSD
```suggestion
  license_family: Other
```

2024-04-04 07:02 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - cython 0.29.36
Wouldn't it be better to use `cython 0.29`?

2024-04-04 07:02 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - numba
Could you comment that `numba` is required here https://github.com/py-why/EconML/blob/v0.15.0/econml/solutions/causal_analysis/_causal_analysis.py#L11?

2024-04-04 21:06 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_0cxe3oysov/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-04 21:11 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_73_9t5s1tj/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-05 10:52 UTC, boldorider4 commented on recipe/meta.yaml
> +    - cython 0.29.36
I don't see why it would be better. `0.29.36` is available for all platforms and all pyver.

2024-04-05 13:13 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - cython 0.29.36
@boldorider4 It's for the future. Pinning to "0.29.36" doesn't bring any benefit and "0.29" is enough.

2024-04-05 13:18 UTC, JeanChristopheMorinPerso approved these changes

2024-04-05 20:20 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_3c5ugpzq94/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-07 06:36 UTC, skupr-anaconda approved these changes

2024-04-08 13:31 UTC, merged

2024-04-08 13:32 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_2034kn3mjc/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>